// import './day01.ts';
// import './day02.ts';
// import './day03.ts';
// import './day04.ts';
// import './day05.ts';
// import './day06.ts';
// import './day07.ts';
// import './day08.ts';
// import './day09.ts';
import './day10.ts';
